-- One table per operational sheet, preserving every named column.
-- Notifications use the four renamed Bookings columns; no extra data tables.
CREATE TABLE IF NOT EXISTS "Bookings" (
  "Sl No" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Booking Reference" text NOT NULL UNIQUE,
  "Created At" timestamptz NOT NULL DEFAULT now(),
  "Apt. No." text NOT NULL,
  "Payment Method" text NOT NULL,
  "Payable Amount" numeric(14,2) NOT NULL CHECK ("Payable Amount" > 0),
  "UPI Txn Id/cheque number" text NOT NULL DEFAULT '',
  "Booking Details" text NOT NULL,
  "Phone Number" text NOT NULL,
  "SMS Status" jsonb NOT NULL DEFAULT '{"state":"pending","attempts":0}',
  "SMS Request ID" text NOT NULL DEFAULT '',
  "SMS Sent At" timestamptz
);
CREATE TABLE IF NOT EXISTS "Booking Items" (
  "Booking Reference" text NOT NULL REFERENCES "Bookings"("Booking Reference"),
  "Created At" timestamptz NOT NULL DEFAULT now(),
  "Apt. No." text NOT NULL,
  "Day Name" text NOT NULL,
  "Meal Type" text NOT NULL,
  "Food Type" text NOT NULL DEFAULT '',
  "Service Type" text NOT NULL DEFAULT '',
  "Quantity" integer NOT NULL CHECK ("Quantity" > 0),
  "Unit Price" numeric(14,2) NOT NULL CHECK ("Unit Price" >= 0),
  "Line Total" numeric(14,2) NOT NULL CHECK ("Line Total" = "Quantity" * "Unit Price"),
  "Source" text NOT NULL CHECK ("Source" IN ('Individual', 'Season Pass')),
  "Day Date" date NOT NULL,
  PRIMARY KEY ("Booking Reference", "Day Date", "Day Name", "Meal Type", "Food Type", "Service Type", "Source", "Unit Price")
);
CREATE TABLE IF NOT EXISTS "Food Menu" (
  "Day" text NOT NULL,
  "Meal Time" text NOT NULL,
  "Menu Veg" text NOT NULL DEFAULT '',
  "Menu Non-Veg" text NOT NULL DEFAULT '',
  "Veg Takeaway Price" numeric(14,2) CHECK ("Veg Takeaway Price" > 0),
  "Veg Dine-In Price" numeric(14,2) CHECK ("Veg Dine-In Price" > 0),
  "Non-veg Takeaway Price" numeric(14,2) CHECK ("Non-veg Takeaway Price" > 0),
  "Non-Veg Dine-In Price" numeric(14,2) CHECK ("Non-Veg Dine-In Price" > 0),
  "Date" date,
  PRIMARY KEY ("Day", "Meal Time"),
  CHECK ("Day" = 'Season Pass' OR "Date" IS NOT NULL)
);
CREATE TABLE IF NOT EXISTS "Donations" (
  "Recipt No." bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "TWR" text NOT NULL,
  "Apt. No." text NOT NULL,
  "NAME" text NOT NULL,
  "Amount" numeric(14,2) CHECK ("Amount" >= 0),
  "Transction ID" text NOT NULL DEFAULT '',
  "Date" date,
  "Ph #" text NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS bookings_apartment ON "Bookings" ("Apt. No.");
CREATE INDEX IF NOT EXISTS bookings_created ON "Bookings" ("Created At");
CREATE UNIQUE INDEX IF NOT EXISTS booking_request ON "Bookings" (("SMS Status"->>'bookingRequestId'));
CREATE INDEX IF NOT EXISTS items_apartment ON "Booking Items" ("Apt. No.");
CREATE INDEX IF NOT EXISTS items_event ON "Booking Items" ("Day Date", "Meal Type");
CREATE INDEX IF NOT EXISTS donations_apartment ON "Donations" ("TWR", "Apt. No.");
CREATE INDEX IF NOT EXISTS pending_sms ON "Bookings" (("SMS Status"->>'state'));
CREATE TABLE IF NOT EXISTS "Resident Master" (
  "Block" text, "Unit No" text, "Name" text, "Intercom" text,
  "Membership Status" text, "Primary Contact" text, "Lives Here" text,
  "Joined On" text, "Has Logged to Adda" text, "Email id" text,
  "Contact number" text, "Paid" text
);
CREATE INDEX IF NOT EXISTS residents_apartment ON "Resident Master" ("Block", "Unit No");

-- Only remove the legacy receipt-number primary key, never the new id key.
-- Receipt numbers are duplicated in the source workbook; retain those values.
DO $$
DECLARE
  receipt_key text;
BEGIN
  SELECT c.conname INTO receipt_key
  FROM pg_constraint c
  JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attname = 'Recipt No.'
  WHERE c.conrelid = '"Donations"'::regclass
    AND c.contype = 'p' AND c.conkey = ARRAY[a.attnum];
  IF receipt_key IS NOT NULL THEN
    EXECUTE format('ALTER TABLE "Donations" DROP CONSTRAINT %I', receipt_key);
  END IF;
END $$;

-- Separate row identifiers support database-editor updates/deletes.
-- Existing ids (including ones added manually in Neon) are preserved on reruns.
ALTER TABLE "Donations" ADD COLUMN IF NOT EXISTS "id" bigint GENERATED ALWAYS AS IDENTITY;
ALTER TABLE "Resident Master" ADD COLUMN IF NOT EXISTS "id" bigint GENERATED ALWAYS AS IDENTITY;
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = '"Donations"'::regclass AND contype = 'p') THEN
    ALTER TABLE "Donations" ADD PRIMARY KEY ("id");
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = '"Resident Master"'::regclass AND contype = 'p') THEN
    ALTER TABLE "Resident Master" ADD PRIMARY KEY ("id");
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS donation_receipt ON "Donations" ("Recipt No.");

ALTER TABLE "Donations" ALTER COLUMN "Amount" DROP NOT NULL;
